### ISSUE TITLE
Run `main.py` raise exception: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by ckf104** [limacv/GaussianSplattingViewer#22]
I run `main.py` and  following exception raises:
```shell
$ python .\main.py                                                                                                                                                                  
Traceback (most recent call last):
  File "C:\Users\24147\anaconda3\Lib\site-packages\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\24147\Documents\GitHub\GaussianSplattingViewer\main.py", line 328, in <module>
    main()
  File "C:\Users\24147\Documents\GitHub\GaussianSplattingViewer\main.py", line 136, in main
    g_renderer_list[BACKEND_OGL] = OpenGLRenderer(g_camera.w, g_camera.h)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\24147\Documents\GitHub\GaussianSplattingViewer\renderer_ogl.py", line 140, in __init__
    vao, buffer_id = util.set_attributes(self.program, ["position"], [self.quad_v])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\24147\Documents\GitHub\GaussianSplattingViewer\util.py", line 171, in set_attributes
    glBufferData(GL_ARRAY_BUFFER, value.nbytes, value.reshape(-1), GL_STATIC_DRAW)
  File "C:\Users\24147\anaconda3\Lib\site-packages\OpenGL\latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\24147\anaconda3\Lib\site-packages\OpenGL\GL\VERSION\GL_1_5.py", line 89, in glBufferData
    return baseOperation( target, size, data, usage )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\24147\anaconda3\Lib\site-packages\OpenGL\latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\24147\anaconda3\Lib\site-packages\OpenGL\wrapper.py", line 681, in wrapperCall
    result = wrappedOperation( *cArguments )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\24147\anaconda3\Lib\site-packages\OpenGL\platform\baseplatform.py", line 402, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: ('argument 3: TypeError: wrong type', (GL_ARRAY_BUFFER, 32, array([-1.,  1.,  1.,  1.,  1., -1., -1., -1.], dtype=float32), GL_STATIC_DRAW))
```

My platform is Win11, I have checked OpenGL version in debugger
```shell
$ glGetString(GL_VERSION)
b'4.3.0 NVIDIA 551.34'
```
How to solve this problem?

**Comment by ckf104** [comment]
Using ordinary python environment instead of conda virtual python environment solves this error.

**Comment by Dimoyok** [comment]
In fact, what you suggest about changing the environment is not a solution, but an illusion caused by your luck. Someone else might change the environment and end up not solving the problem. Perhaps you got lucky because you accidentally installed a different version of PyOpenGL on a different environment. 

There is a better solution. This error clearly says that the function expects one data type and receives another. In fact, it wants to explicitly get a pointer. You just need to replace the line (and all other similar ones) with something like:
```
data_ptr = value.ctypes.data_as(ctypes.POINTER(ctypes.c_float))
glBufferData(GL_ARRAY_BUFFER, value.nbytes, data_ptr, GL_STATIC_DRAW)
```
