### ISSUE TITLE
VSync is not supported

### ISSUE THREAD

**Issue by zuoweic** [limacv/GaussianSplattingViewer#23]
VSync is not supported
VSync is not supported
VSync is not supported
VSync is not supported
VSync is not supported
Traceback (most recent call last):
  File "/home/zw/ws/GaussianSplattingViewer/main.py", line 328, in <module>
    main()
  File "/home/zw/ws/GaussianSplattingViewer/main.py", line 202, in main
    gaussians = util_gau.load_ply(file_path)
  File "/home/zw/ws/GaussianSplattingViewer/util_gau.py", line 77, in load_ply
    assert len(extra_f_names)==3 * (max_sh_degree + 1) ** 2 - 3
AssertionError

I don't know why.... when i open a .ply document.

**Comment by RyanJayWu** [comment]
I commented out that line and it worked. :)
