### ISSUE TITLE
Error GLIBC_2.33

### ISSUE THREAD

**Issue by weihaosky** [limacv/GaussianSplattingViewer#6]
Hi, thanks for this excellent work!
But when I run main.py, an error occurs:
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import util
  File "/home/weihao/Documents/github/human/gs_viewers/GaussianSplattingViewer/util.py", line 4, in <module>    import glm
  File "/home/weihao/anaconda3/envs/gs/lib/python3.8/site-packages/glm/__init__.py", line 1, in <module>
    from ._glm import *
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/will/anaconda3/envs/gs/lib/python3.8/site-packages/glm/_glm.so)
```
May I ask what is the cause and how to solve it? Thanks!

**Comment by limacv** [comment]
Did you `pip install glm`? If so, could you try install `pip install PyGLM` instead because `PyGLM` is the actual python wrapper for GL math library.
